services:
  frontend:
    image: infox:2.2
    build: .
    volumes:
      - ./frontend:/infox
    ports:
      - 3000:3000
    command: bash -c "npm run dev"
    depends_on:
      - backend
  backend:
    image: infox:2.2
    volumes:
      - ./backend:/infox
    ports:
     - 5000:5000
    command: bash -c "uvicorn src.gpt.gpt_api:app --reload --host 0.0.0.0 --port 5000"