services:
  frontend:
    image: infox:1.0
    build: .
    ports:
      - 3000:3000
    command: bash -c "npm run dev"
  backend:
    image: infox:1.0
    build: .
    ports:
     - 5000:5000
    command: bash -c "uvicorn src.gpt.gpt_api:app --reload --host 0.0.0.0 --port 5000"